### ISSUE TITLE
Support gettimeofday

### ISSUE THREAD

**Issue by shouze** [rezzza/TimeTraveler#2]
[gettimeofday](http://fr2.php.net/gettimeofday)

**Comment by tyx** [comment]
Who use this crap ?

**Comment by stephpy** [comment]
Yep ! WHO ? Come on guys !!

![](http://media.giphy.com/media/lMidb587Myjtu/giphy.gif)

**Comment by shouze** [comment]
used in rhumsa uuid generator lib ;)

**Comment by armandabric** [comment]
I agree but WTF ?!? http://fr2.php.net/manual/en/function.gettimeofday.php
